### ISSUE TITLE
pluto should have an upper limit for 1)cpu cores used, 2)workers and 3)file parts

### ISSUE THREAD

**Issue by omac777** [ishanjain28/pluto#1]
The number of parts having no upper limit needs to some limit. Your hardware has constraints and your software needs respect those constraints for optimal use.

I see nothing like "runtime.GOMAXPROCS(runtime.NumCPU())" in your code.  That actually is too simple.  It should actually use more like 80% of runtime.NumCPU() to let the OS breathe.  If your computer usually is busy with other things, then you should lower that 80% even more.  In other words, the number of cores your cpu has might be a good limit, but your operating system needs a few itself in order to behave properly so it's best to not use all the cores all the time.  

For example if your CPU has 8 cores, the context switching that happens when flipping between parts > 8 cores caused by having > 8 parts will result in actually slower performance.

You shouldn't be basing your number of workers on the number of parts.  THEY ARE DIFFERENT.
What if the file you are loading is 2 TB? You don't have enough RAM to cover that nor the number of workers.  You do need constraints for cpu cores, workers, parts to provide for the smooth operation of your pluto.

**Comment by ishanjain28** [comment]
@omac777 Thanks for opening an issue. 

I've set `GOMAXPROCS` to 50%.

The CLI tool lets you specify number of parts. 

And today in one of the [commits](https://github.com/ishanjain28/pluto/commit/8688ecd8dbcda008e5719b5263a5448628b65572) I tweaked the code a little bit. 

So now, It reads 64 Kilobytes from a connection and writes it to the `saveFile`. This way the size of file doesn't really matters and the RAM usage is about (64 kilobytes * number of parts + whatever it takes to run the rest of the program) and CPU usage stays around 1-2%.


I tested it on a machine by downloading a 25GB file with 100 parts with 256MB Ram multiple times and the RAM usage only goes to about 20MB. 

Please try out the latest version, It should work correctly. But if you do run in any trouble, Feel free to create an issue. :)
